In [39]:
import numpy as np

In [40]:
#1D array
arr1 = np.array([1,2,3,4,5])

In [41]:
#2D array

arr2 =np.array([[1,2],[3,4]])

In [42]:
arr2

array([[1, 2],
       [3, 4]])

In [43]:
#3D array

arr3 =np.array([[[1,2],[3,4]],[[10,20],[30,40]]])

In [44]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [45]:
#check number of dimensions ndim

arr1.ndim

1

In [46]:
arr2.ndim

2

In [47]:
arr3.ndim

3

In [48]:
arr1

array([1, 2, 3, 4, 5])

In [49]:
arr1[0]

1

In [50]:
arr1[3]

4

In [51]:
arr2

array([[1, 2],
       [3, 4]])

In [52]:
arr2[1,1]

4

In [53]:
arr2[0,1]

2

In [54]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [55]:
#access 20

arr3[1,0,1]

20

In [56]:
#access the number 3
# for 3rd dim : 0
# for 2nd dim row: 1
# for 2nd dim col: 0

arr3[0,1,0]

3

In [57]:
#access 30

arr3[1,1,0]





30

In [58]:
#check shape

arr1.shape

(5,)

In [59]:
arr2.shape

(2, 2)

In [60]:
arr3.shape

(2, 2, 2)

In [61]:
#reshape

array1 = np.array([30,22,44,55,66,77])

In [62]:
array1.reshape(3,2)

array([[30, 22],
       [44, 55],
       [66, 77]])

In [63]:
#sort

s1 = np.sort(array1)

In [64]:
s1

array([22, 30, 44, 55, 66, 77])

In [65]:
#joining of arrays

a1 = np.array([11,22,33])
a2 = np.array([33,44,55])

In [66]:
a3 = np.concatenate((a1,a2))

In [67]:
a3

array([11, 22, 33, 33, 44, 55])

In [68]:
a4 = np.hstack((a1,a2))

In [69]:
a4

array([11, 22, 33, 33, 44, 55])

In [70]:
a5 = np.vstack((a1,a2))

In [71]:
a5

array([[11, 22, 33],
       [33, 44, 55]])

In [72]:
#where

np.where(arr3==40)

(array([1], dtype=int64), array([1], dtype=int64), array([1], dtype=int64))

In [73]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [74]:
arr3[1,1,1]

40